/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   names.hpp                                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: user42 <user42@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/05/26 16:21:33 by user42            #+#    #+#             */
/*   Updated: 2021/05/27 12:34:37 by user42           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <iostream>

#include <cstdlib>
#include <iostream>
#include <ctime>

std::string get_randomName(void);

const std::string   g_names[] = {
"Zachary",
"Kalan",
"Jane",
"Cerise",
"Kent",
"Sophia",
"Byron",
"Georgina",
"Timothy",
"Irene",
"Brighton",
"Avery",
"Naveen",
"Raven",
"Ann",
"Caylen",
"Selene",
"Kathryn",
"Adelaide",
"Damien",
"Tavian",
"Zoe",
"Carlen",
"Edward",
"Breean",
"Dante",
"June",
"Adele",
"Benjamin",
"Eli",
"Louis",
"Grant",
"Berlynn",
"Troy",
"Meaghan",
"Xavier",
"Luke",
"Lydon",
"Josiah",
"Devon",
"Madeleine",
"Glenn",
"Caprice",
"Brendon",
"Daniel",
"Aiden",
"Rhett",
"Sue",
"Gregory",
"Dawn",
"Hugh",
"Coreen",
"Miranda",
"Brooke",
"Seth",
"Bram",
"Brett",
"Tobias",
"David",
"Vivian",
"Justin",
"Kate",
"Randall",
"Malachi",
"Damon",
"Lee",
"Verena",
"Ricardo",
"Harrison",
"William",
"Leo",
"Neil",
"Conrad",
"Brandt",
"Dex",
"Will",
"Blaise",
"Tyson",
"Jolee",
"Jordon",
"Blake",
"Joseph",
"Bailee",
"Dominick",
"Juliet",
"James",
"Love",
"Naomi",
"Claudia",
"Nadeen",
"Elijah",
"Abigail",
"Isaac",
"Clark",
"Sheridan",
"Elias",
"Ashten",
"Myron",
"Carelyn",
"Silvia"
};
